export const orders = [
    {
        key: 0,
        customer: 'Juan Dela Cruz',
        transactionDate: '2021-10-10',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'John Boyd',
    },
    //generate with different customers and dates and everything else
    {
        key: 1,
        customer: 'John Smith',
        transactionDate: '2021-10-10',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'Sarah Johnson',
    },
    {
        key: 2,
        customer: 'Mary Williams',
        transactionDate: '2021-10-11', 
        paymentStatus: 'UnPaid',
        fulfillmentStatus: 'UnFulfilled',
        handledby: 'Michael Brown',
    },
    {
        key: 3,
        customer: 'Robert Jones',
        transactionDate: '2021-10-12',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'Emily Davis',
    },
    {
        key: 4,
        customer: 'Patricia Miller',
        transactionDate: '2021-10-13',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled', 
        handledby: 'James Wilson',
    },
    {
        key: 5,
        customer: 'Jennifer Garcia',
        transactionDate: '2021-10-14',
        paymentStatus: 'UnPaid',
        fulfillmentStatus: 'UnFulfilled',
        handledby: 'David Martinez',
    },
    {
        key: 6,
        customer: 'Michael Anderson',
        transactionDate: '2021-10-15',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'Lisa Taylor',
    },
    {
        key: 7,
        customer: 'Elizabeth Thomas',
        transactionDate: '2021-10-16',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'Kevin Moore',
    },
    {
        key: 8,
        customer: 'William Jackson',
        transactionDate: '2021-10-17',
        paymentStatus: 'UnPaid',
        fulfillmentStatus: 'UnFulfilled',
        handledby: 'Michelle Lee',
    },
    {
        key: 9,
        customer: 'Barbara White',
        transactionDate: '2021-10-18',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'Christopher Harris',
    },
    {
        key: 10,
        customer: 'Richard Martin',
        transactionDate: '2021-10-19',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'Amanda Thompson',
    },
    {
        key: 11,
        customer: 'Susan Clark',
        transactionDate: '2021-10-20',
        paymentStatus: 'UnPaid',
        fulfillmentStatus: 'UnFulfilled',
        handledby: 'Daniel Rodriguez',
    },
    {
        key: 12,
        customer: 'Joseph Lewis',
        transactionDate: '2021-10-21',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'Jessica Walker',
    },
    {
        key: 13,
        customer: 'Maria Makiling',
        transactionDate: '2021-10-12',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'Napoleon Bonaparte',
    },
    {
        key: 14,
        customer: 'Juan Dela Cruz',
        transactionDate: '2021-10-13',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'John Boyd',
    },
    {
        key: 15,
        customer: 'Pedro Penduko',
        transactionDate: '2021-10-14',
        paymentStatus: 'UnPaid',
        fulfillmentStatus: 'UnFulfilled',
        handledby: 'Albert Einstein',
    },
    {
        key: 16,
        customer: 'Maria Makiling',
        transactionDate: '2021-10-15',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'Napoleon Bonaparte',
    },
    {
        key: 17,
        customer: 'Juan Dela Cruz',
        transactionDate: '2021-10-16',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'John Boyd',
    },
    {
        key: 18,
        customer: 'Pedro Penduko',
        transactionDate: '2021-10-17',
        paymentStatus: 'UnPaid',
        fulfillmentStatus: 'UnFulfilled',
        handledby: 'Albert Einstein',
    },
    {
        key: 19,
        customer: 'Maria Makiling',
        transactionDate: '2021-10-18',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'Napoleon Bonaparte',
    },
    {
        key: 20,
        customer: 'Juan Dela Cruz',
        transactionDate: '2021-10-19',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'John Boyd',
    },
    {
        key: 21,
        customer: 'Pedro Penduko',
        transactionDate: '2021-10-20',
        paymentStatus: 'UnPaid',
        fulfillmentStatus: 'UnFulfilled',
        handledby: 'Albert Einstein',
    },
    {
        key: 22,
        customer: 'Maria Makiling',
        transactionDate: '2021-10-21',
        paymentStatus: 'Paid',
        fulfillmentStatus: 'Fulfilled',
        handledby: 'Napoleon Bonaparte',
    }

    

];
