import { PurchaseOrderLine } from "@/src/entities/purchase-order-line/type/purchase-order-line";
import { ReceivedItem } from "@/src/entities/received-item/type/received-item";

/**
 * Converts a purchase order line to a delivery line.
 * This is used when a purchase order line is added to the delivery.
 * @param poLine - The purchase order line to convert to new delivery line
 * @returns delivery line literal. Id is set to 0, as it will be generated by the server.
 */
export const buildDeliveryLines = (poLine: PurchaseOrderLine): ReceivedItem => {
    return {
        id: 0,
        product: {
            id: poLine.productId,
            name: poLine.product?.name ?? '',
            costPrice: poLine.product?.costPrice ?? 0,
            price: poLine.product?.price ?? 0,
            isBundle: poLine.product?.isBundle ?? false,
            stocks: poLine.product?.stocks ?? 0,
            unitType: poLine.product?.unitType ?? '',
            brand: poLine.product?.brand ?? '',
            bundleType: poLine.product?.bundleType ?? undefined,
            bundleQuantity: poLine.product?.bundleQuantity ?? undefined,
            originalProductId: poLine.product?.originalProductId ?? undefined,
            category: poLine.product?.category ?? '',
        },
        quantity: poLine.receivedQuantity ?? 0,
        total: poLine.totalPrice,
        manualPrice: poLine.basePrice,
        discountPercentage: poLine.percentageDiscount,
        discountFlat: poLine.flatDiscount,
    };
}
